In [2]:
import numpy as np

cost = np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]])

from scipy.optimize import linear_sum_assignment

row_ind, col_ind = linear_sum_assignment(cost)
print(row_ind)
print(col_ind)

print(cost[row_ind, col_ind])


[0 1 2]
[1 0 2]
[1 2 2]
